Add basic model and repositories
Java4Wro/ticket-reservations pull request #5
Opened 2017-11-13 16:55 UTC by drG0n20

2017-11-13 17:00 UTC, xenteros requested changes
Na razie jest dobrze. Jedyna rzecz do poprawki to cena, która powinna być big decimalem.

2017-11-13 17:00 UTC, xenteros commented on src/main/java/com/github/java4wro/ticket/Ticket.java
> +    private Integer price;
price should be BigDecimal

2017-11-13 17:55 UTC, xenteros requested changes

2017-11-13 17:55 UTC, xenteros commented on pom.xml
> +        <dependency>
Nie ma potrzeby dodawać zależności po dwa razy

2017-11-13 17:55 UTC, xenteros commented on pom.xml
> +            <version>2.2.2</version>
brakuje exclude mapstructa - będzie się gryźć

2017-11-13 17:55 UTC, xenteros commented on src/main/java/com/github/java4wro/dto/EventDTO.java
> +    private Integer eventPrice;
Tutaj też BigDecimal

2017-11-13 17:55 UTC, xenteros commented on src/main/java/com/github/java4wro/event/Event.java
> +    private Integer basicPrice;
Tutaj też BD

2017-11-13 18:51 UTC, piotrhor11 commented on pom.xml
> +            <version>2.2.2</version>
Na razie niezaimplementowane, bo nie zaobserwowaliśmy problemu.

2017-11-20 18:06 UTC, piotrhor11 commented
Database models' integration

2017-11-21 16:45 UTC, xenteros approved these changes

2017-11-21 17:09 UTC, merged